version: "3"
services:
  backend:
    container_name: flask_backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend/
    ports:
      - 5000:5000
  frontend:
    container_name: react_frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend/
      - ./backend:/usr/src/backend/
    ports:
      - 3000:3000
